QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 100 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 2500 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },
	lumberjack = { label = 'lumberjack', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },

	police = {
		label = 'Law Enforcement',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'INTERN', payment = 3500 },
			['1'] = { name = 'CONSRABLE', payment = 3600 },
			['2'] = { name = 'ASI', payment = 3700 },
			['3'] = { name = 'SURGENT', payment = 3800 },
			['4'] = { name = 'SUB INSPECTOR', payment = 3900 },
			['5'] = { name = 'INSPECTOR', payment = 4000 },
			['6'] = { name = 'ASP', payment = 4100 },
			['7'] = { name = 'SP', payment = 4200 },
			['8'] = { name = 'ADIG', payment = 4300 },
			['9'] = { name = 'DIG', isboss = true, payment = 4400 },
			['10'] = { name = 'AIGP', isboss = true, payment = 4500 },
			['11'] = { name = 'IGP', isboss = true, payment = 4600 },
			['12'] = { name = 'ADMIN', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'INTERN', payment = 3600 },
			['1'] = { name = 'DOCTOR', payment = 3700 },
			['2'] = { name = 'SENIOR DOCTOR', payment = 3800 },
			['3'] = { name = 'SURGEON', payment = 3900 },
			['4'] = { name = 'SENIOR SURGEON', payment = 4000 },
			['5'] = { name = 'PROFESSOR', payment = 4100 },
			['6'] = { name = 'MEDICAL SPECIALIST', payment = 4200 },
			['7'] = { name = 'Assistant Chief', payment = 4300 },
			['8'] = { name = 'Deputy Chief', isboss = true, payment = 4400 },
			['9'] = { name = 'Chief of EMS',isboss = true, payment = 4500 },
		--	['10'] = { name = '', isboss = true,  payment = 4600 },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 3000 },
			['1'] = { name = 'Novice', payment = 3200 },
			['2'] = { name = 'Experienced', payment = 3400 },
			['3'] = { name = 'Advanced', payment = 3600 },
			['4'] = { name = 'Manager', isboss = true, payment = 3800 },
		},
	},
	--[[ mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	}, ]]
	--[[ beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	}, ]]
	unicorn = {
		label = 'unicorn Mamas',
		type = 'unicorn',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	burgershot = {
		label = "Burgershot",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 75 },
			['2'] = { name = "Burger Flipper", payment = 100 },
			['3'] = { name = "Manager", payment = 125 },
			['4'] = { name = "Owner", isboss = true, payment = 150 },
		},
	},	
	catcafe = {
		label = "Cat Cafe",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 75 },
			['2'] = { name = "Flipper", payment = 100 },
			['3'] = { name = "Manager", payment = 125 },
			['4'] = { name = "Owner", isboss = true, payment = 150 },
		},
	},
}
